### ISSUE TITLE
Problème avec les créneaux 

### ISSUE THREAD

**Issue by Maxime1003** [Sirlefou1/GRR2#39]
Bonjour,
J'ai installé la version suivante de grr : https://github.com/Sirlefou1/GRR2.
J'ai ajouté un domaine "Audio" que j'ai configuré avec des "créneaux de réservation basés sur des intitulés pré-définis."
Le problème est le suivant : lorsque que j'ajoute une réservation pour une ressource et que je vais voir le calendrier de la ressource. Il m'indique que la ressource est réservé de 12:00 à 12:03. De plus la ressource est inscrite uniquement sur le premier créneau (alors que j'ai réservé sur 3 créneaux).
Et pour terminer, toujours sur le calendrier de la ressource, le 2ème créneau du dimanche est tout vert et impossible d'ajouter une réservation pour ce créneau.
Je vous ajoute 3 captures pour expliquer mon problème.
Cette installation de grr étant en ligne (encore en test) je peux vous fournir des logins pour d’éventueles tests
![grr_prob1](https://cloud.githubusercontent.com/assets/10549036/5760555/cd03ade2-9cd5-11e4-99f0-6f7f96a9f7a4.PNG)
![grr_prob2](https://cloud.githubusercontent.com/assets/10549036/5760553/ccfca254-9cd5-11e4-99a3-dd213332946b.PNG)
![grr_prob4](https://cloud.githubusercontent.com/assets/10549036/5760554/cd037390-9cd5-11e4-8188-315d9e368b5d.PNG)

**Comment by eterroux** [comment]
Même problématique de mon côté... J'ai temporairement redirigé la vue "semaine/ressource" (fichier week.php) vers la vue "semaine" (fichier week_all.php), car les réservations ne s'affichent pas correctement lorsqu'on utilise des créneaux... Sûrement de quoi à faire dans le fichier "week.php"...

**Comment by Sirlefou1** [comment]
Probleme corriger dans le dernier commit https://github.com/Sirlefou1/GRR2/commit/bf3c34d52aa83824fca28999ce1f37b6dad09169
